# Generated by Django 5.0 on 2024-01-30 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Element/Attribute')),
            ],
            options={
                'verbose_name': 'api_cards_attribute',
                'verbose_name_plural': 'api_cards_attributes',
                'db_table': 'api_cards_attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Card Rarity')),
            ],
            options={
                'verbose_name': 'api_cards_rarity',
                'verbose_name_plural': 'api_cards_rarities',
                'db_table': 'api_cards_rarities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Card Subtype')),
                ('card_family', models.CharField(max_length=5, verbose_name='Card Type')),
            ],
            options={
                'verbose_name': 'api_cards_subtype',
                'verbose_name_plural': 'api_cards_subtypes',
                'db_table': 'api_cards_subtypes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Card Type')),
            ],
            options={
                'verbose_name': 'api_cards_type',
                'verbose_name_plural': 'api_cards_types',
                'db_table': 'api_cards_types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('stars', models.CharField(default='', max_length=2, null=True, verbose_name='Stars')),
                ('allowed', models.CharField(default='', max_length=1, null=True, verbose_name='Ammount Allowed')),
                ('url_img', models.TextField(null=True, verbose_name='Image URL')),
                ('card_description', models.TextField(null=True, verbose_name='Description')),
                ('card_pendulum_description', models.TextField(null=True, verbose_name='Pendulum Description')),
                ('card_atk', models.CharField(max_length=20, null=True, verbose_name='Attack Points')),
                ('card_def', models.CharField(blank=True, max_length=20, null=True, verbose_name='Defense Points')),
                ('card_link', models.CharField(max_length=3, null=True, verbose_name='Link Rank')),
                ('obtain_method', models.TextField(default='', null=True, verbose_name='Obtain Method')),
                ('pendulum_scales', models.CharField(default='', max_length=10, null=True, verbose_name='Scales')),
                ('attribute', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_attribute', verbose_name='Card Attribute')),
                ('card_rarity', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_rarity')),
                ('card_subtype', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_subtype', verbose_name='Card Race')),
                ('card_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_type', verbose_name='Card Type')),
            ],
            options={
                'verbose_name': 'api_card',
                'verbose_name_plural': 'api_cards',
                'db_table': 'api_cards',
                'ordering': ['id'],
            },
        ),
    ]
