# Generated by Django 5.0 on 2023-12-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='attribute',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_atk',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_def',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_link',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_pendulum_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_special_subtype',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_special_type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cards',
            name='url_img',
            field=models.TextField(null=True),
        ),
    ]
