# Generated by Django 5.0 on 2024-01-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='url_img',
            field=models.TextField(null=True, verbose_name='Image URL'),
        ),
    ]
