# Generated by Django 5.0 on 2023-12-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cards_attribute_alter_cards_card_atk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_rarity',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
