# Generated by Django 5.0 on 2024-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_atk',
            field=models.CharField(max_length=20, null=True, verbose_name='Attack Points'),
        ),
    ]
