# Generated by Django 5.0 on 2023-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cards_card_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_rarity',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
