# Generated by Django 5.0 on 2024-01-19 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_cards_card_atk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='attribute',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_attribute', verbose_name='Card Attribute'),
        ),
    ]
