# Generated by Django 5.0 on 2024-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_cards_card_special_subtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='pendulum_scales',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Scaless'),
        ),
    ]
