# Generated by Django 5.0 on 2024-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cards_obtain_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card_def',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Defense Points'),
        ),
    ]
