# Generated by Django 5.0 on 2024-01-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cards_pendulum_scales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Element/Attribute')),
            ],
            options={
                'verbose_name': 'api_cards_attribute',
                'verbose_name_plural': 'api_cards_attributes',
                'db_table': 'api_cards_attributes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Card Rarity')),
            ],
            options={
                'verbose_name': 'api_cards_rarity',
                'verbose_name_plural': 'api_cards_rarities',
                'db_table': 'api_cards_rarities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Card Subtype')),
            ],
            options={
                'verbose_name': 'api_cards_subtype',
                'verbose_name_plural': 'api_cards_subtypes',
                'db_table': 'api_cards_subtypes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Card_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Card Type')),
            ],
            options={
                'verbose_name': 'api_cards_type',
                'verbose_name_plural': 'api_cards_types',
                'db_table': 'api_cards_types',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card_description',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card_special_type',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='url_img',
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_atk',
            field=models.CharField(help_text='text', max_length=20, verbose_name='Attack Points'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_def',
            field=models.CharField(help_text='text', max_length=20, null=True, verbose_name='Defense Points'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_link',
            field=models.CharField(help_text='text', max_length=3, null=True, verbose_name='Link Rank'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_pendulum_description',
            field=models.TextField(help_text='text', null=True, verbose_name='Pendulum Description'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='pendulum_scales',
            field=models.CharField(default='', help_text='text', max_length=10, null=True, verbose_name='Scaless'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='stars',
            field=models.CharField(default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_attribute'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_rarity',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_rarity'),
        ),
        migrations.AddField(
            model_name='cards',
            name='card_subtype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_subtype'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_type'),
        ),
    ]
