# Generated by Django 5.0 on 2024-01-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_card_subtype_card_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='obtain_method',
            field=models.CharField(default='', null=True, verbose_name='Obtain Method'),
        ),
        migrations.AlterField(
            model_name='card_subtype',
            name='card_family',
            field=models.CharField(max_length=1, verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_attribute', verbose_name='Card Attribute'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_atk',
            field=models.CharField(max_length=20, verbose_name='Attack Points'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_def',
            field=models.CharField(max_length=20, null=True, verbose_name='Defense Points'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_link',
            field=models.CharField(max_length=3, null=True, verbose_name='Link Rank'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_pendulum_description',
            field=models.TextField(null=True, verbose_name='Pendulum Description'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_subtype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_subtype', verbose_name='Card Race'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='card_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cards.card_type', verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='pendulum_scales',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Scales'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='stars',
            field=models.CharField(default='', max_length=2, null=True, verbose_name='Stars'),
        ),
    ]
