# Generated by Django 5.0 on 2024-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cards_obtain_method_alter_card_subtype_card_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_subtype',
            name='card_family',
            field=models.CharField(max_length=5, verbose_name='Card Type'),
        ),
    ]
