# Generated by Django 5.0 on 2024-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_alter_card_subtype_card_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='allowed',
            field=models.CharField(default='', max_length=1, null=True, verbose_name='Ammount Allowed'),
        ),
    ]
