# Generated by Django 5.0 on 2023-12-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'api_user', 'verbose_name_plural': 'api_users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_users',
        ),
    ]
